CREATE TABLE STATE (
  FF_SESSIONS int DEFAULT 0,
  FF_ERRORS   int DEFAULT 0,
  FF_IMAGES   int DEFAULT 0,
  FF_POSTS    int DEFAULT 0,
  WP_SESSIONS int DEFAULT 0,
  WP_ERRORS   int DEFAULT 0,
  WEB_CALLS   int DEFAULT 0
);
